version: '3.8'

services:
  dummy-webservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
